export const API_ROOT = 'http://localhost:8008'

export const MODAL_ACTION_CLOSE = 'MODAL_ACTION_CLOSE'
export const MODAL_ACTION_CONFIRM = 'MODAL_ACTION_CONFIRM'

//GENERAL DATA OF CAKE
export const SIZE = 'SIZE'
export const SPONGE_TASTE = 'SPONGE_TASTE'
export const JAM_TASTE = 'JAM_TASTE'

export const CAKE_CATEGORY_ID = '63c4226d83fed687f3a3f68a'

export const CAKE_TYPE_SELECT_POPOVER_TYPE_CAKETYPE = 'CAKE_TYPE_SELECT_POPOVER_TYPE_CAKETYPE'
export const CAKE_TYPE_IDS_ACTION_PUSH = 'CAKE_TYPE_IDS_ACTION_PUSH'
export const CAKE_TYPE_IDS_ACTION_REMOVE = 'CAKE_TYPE_IDS_ACTION_REMOVE'

export const CAKE_STYLE_SELECT_POPOVER_TYPE_CAKESTYLE = 'CAKE_STYLE_SELECT_POPOVER_TYPE_CAKESTYLE'
export const CAKE_STYLE_IDS_ACTION_PUSH = 'CAKE_STYLE_IDS_ACTION_PUSH'
export const CAKE_STYLE_IDS_ACTION_REMOVE = 'CAKE_STYLE_IDS_ACTION_REMOVE'

export const CAKE_SIZE_SELECT_POPOVER_TYPE_CAKESIZE = 'CAKE_SIZE_SELECT_POPOVER_TYPE_CAKESIZE'
export const CAKE_PRICE_BY_SIZES_ACTION_PUSH = 'CAKE_PRICE_BY_SIZES_ACTION_PUSH'
export const CAKE_PRICE_BY_SIZES_ACTION_REMOVE = 'CAKE_PRICE_BY_SIZES_ACTION_REMOVE'

export const GOOGLE_MAP_API_KEY = 'AIzaSyB1k8NQGwLyOAcuIEZ0bq6ir4BbobDvqf4'